platform :ios, '11.0'

target 'SimpleChat' do
	# Pods for SimpleChat
	pod 'GoogleSignIn', '= 4.0.2'
	pod 'Firebase/Database', '= 3.16.0'
	pod 'Firebase/Auth', '= 3.16.0'   
    pod 'MSAL','= 0.1.4'
end

