# MSAL Requires iOS 10.0
platform :ios, '10.0'

use_frameworks!

target 'QuickStart' do
	# Pods for QuickStart (Using Google Sign In)
	pod 'GoogleSignIn', '= 4.0.2'
	pod 'Firebase/Database', '= 3.16.0'
	pod 'Firebase/Auth', '= 3.16.0'
    pod 'MSAL', '= 0.1.4'
end


